/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppFatoresRouteImport } from './routes/app.fatores'
import { Route as AppEquipeRouteImport } from './routes/app.equipe'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppComissoesRouteImport } from './routes/app.comissoes'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppFatoresRoute = AppFatoresRouteImport.update({
  id: '/fatores',
  path: '/fatores',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComissoesRoute = AppComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comissoes': typeof AppComissoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fatores': typeof AppFatoresRoute
  '/app/pipeline': typeof AppPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comissoes': typeof AppComissoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fatores': typeof AppFatoresRoute
  '/app/pipeline': typeof AppPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comissoes': typeof AppComissoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fatores': typeof AppFatoresRoute
  '/app/pipeline': typeof AppPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/comissoes'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/fatores'
    | '/app/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/comissoes'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/fatores'
    | '/app/pipeline'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/comissoes'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/fatores'
    | '/app/pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fatores': {
      id: '/app/fatores'
      path: '/fatores'
      fullPath: '/app/fatores'
      preLoaderRoute: typeof AppFatoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comissoes': {
      id: '/app/comissoes'
      path: '/comissoes'
      fullPath: '/app/comissoes'
      preLoaderRoute: typeof AppComissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppClientesRoute: typeof AppClientesRoute
  AppComissoesRoute: typeof AppComissoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppFatoresRoute: typeof AppFatoresRoute
  AppPipelineRoute: typeof AppPipelineRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppClientesRoute: AppClientesRoute,
  AppComissoesRoute: AppComissoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppFatoresRoute: AppFatoresRoute,
  AppPipelineRoute: AppPipelineRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
